### ISSUE TITLE
[Tutorial] nginx forward proxy for socket.io

### ISSUE THREAD

**Issue by Local9** [SnailyCAD/live-map#16]
For those using nginx, after you have SnailyCAD up and running with a secure domain (https), you'll need to add a forward proxy from the same location as the CAD URL. 

In the nginx configuration for the CAD Client (example would be `cad-client` if you followed the tutorials), add the following after the `location /` block (you should then have two location blocks in the configuration), **Remember** to change the `FIVEM_SERVER_IP` to the IP of your FiveM server. If you have changed the port for the live map resource, make sure to change the port below to match.

```conf
  location /socket.io/ {
    proxy_pass http://FIVEM_SERVER_IP:30121$uri$is_args$args;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
  }
```

After you have added this, make sure to run `nginx -t` in your command line to test your configurations before running `service nginx reload`. Now you can update the CAD Settings to set your Live Map URL the same as your CAD Client url, for example `https://cad.example.com`.

**Comment by Dev-CasperTheGhost** [comment]
@Local9, to what page should this be added in the docs?
